export const ACHIEVEMENT_META = [
  {
    id: 'preset-1',
    key: 'first_contact',
    name: 'First Contact',
    description: 'Complete your first mission',
    icon: '🚀',
    xpReward: 25,
  },
  {
    id: 'preset-2',
    key: 'quick_draw',
    name: 'Flight Hours',
    description: 'Play 5 missions total',
    icon: '⚡',
    xpReward: 50,
  },
  {
    id: 'preset-3',
    key: 'untouchable',
    name: 'Shielded Run',
    description: 'Complete any mission with at least 2 shield left',
    icon: '🛡️',
    xpReward: 75,
  },
  {
    id: 'preset-4',
    key: 'combo_master',
    name: 'Combo Master',
    description: 'Reach a 10x combo multiplier in a single mission',
    icon: '🔥',
    xpReward: 60,
  },
  {
    id: 'preset-5',
    key: 'star_commander',
    name: 'Star Commander',
    description: 'Complete all 3 missions',
    icon: '🏆',
    xpReward: 150,
  },
  {
    id: 'preset-6',
    key: 'stardust_collector',
    name: 'Stardust Collector',
    description: 'Earn 250 or more Stardust in total',
    icon: '💎',
    xpReward: 100,
  },
];
