export const ENEMY_CONTENT = {
  meteor: {
    key: 'meteor',
    label: 'Meteor',
    points: 10,
    summary: 'Basic level 1 target. Destroy it for points and combo.',
  },
  mine: {
    key: 'mine',
    label: 'Mine',
    points: -15,
    summary: 'Hazard in every level. Shooting a mine costs score and resets combo, but it does not damage the forcefield.',
  },
  ghost_boy: {
    key: 'ghost_boy',
    label: 'Ghost Boy',
    points: 20,
    summary: 'Fast spectral target in level 2.',
  },
  king_boo: {
    key: 'king_boo',
    label: 'King Boo',
    points: 30,
    summary: 'Higher-value level 2 target.',
  },
  chuck: {
    key: 'chuck',
    label: 'Chuck',
    points: 50,
    summary: 'Level 3 threat. Takes 1 shot to destroy.',
  },
  boss: {
    key: 'boss',
    label: 'Red Angrybird',
    points: 100,
    summary: 'Level 3 boss target. Takes 3 shots to destroy.',
  },
  energy: {
    key: 'energy',
    label: 'Energy Orb',
    points: 15,
    summary: 'Bonus pickup that grants score.',
  },
  stardust: {
    key: 'stardust',
    label: 'Stardust Core',
    points: 25,
    summary: 'Bonus pickup that grants score and extra time.',
  },
};

export const MISSION_CATALOG = [
  {
    id: 1,
    marker: '01',
    name: 'The Minefield',
    difficulty: 'Easy',
    previewDesc: 'Learn the tunnel against meteors and mines.',
    selectDesc: 'Classic survival. Learn to dodge meteors and mines.',
    description: 'Classic survival sector focused on meteors and mines.',
    duration: 60,
    waves: 8,
    speed: 0.85,
    requiredLevel: 1,
    baseXP: 30,
    baseStardust: 20,
    enemyTypes: ['meteor', 'mine'],
  },
  {
    id: 2,
    marker: '02',
    name: 'Specter Run',
    difficulty: 'Medium',
    previewDesc: 'Faster waves with ghost targets and tighter gaps.',
    selectDesc: 'Faster waves with ghost targets, tight gaps, and live mines.',
    description: 'Faster mission with ghost targets, King Boo threats, and live mines.',
    duration: 48,
    waves: 14,
    speed: 1.38,
    requiredLevel: 1,
    baseXP: 60,
    baseStardust: 40,
    enemyTypes: ['ghost_boy', 'king_boo', 'mine'],
  },
  {
    id: 3,
    marker: '03',
    name: 'The Absurd Threat',
    difficulty: 'Hard',
    previewDesc: 'Maximum speed, Red Angrybird pressure, almost no recovery.',
    selectDesc: 'Maximum speed. Survive Chuck, the Red Angrybird, and the minefield.',
    description: 'Maximum-speed mission with Chuck, the Red Angrybird boss, and constant mine pressure.',
    duration: 42,
    waves: 18,
    speed: 1.72,
    requiredLevel: 1,
    baseXP: 100,
    baseStardust: 70,
    enemyTypes: ['chuck', 'boss', 'mine'],
  },
];
